image: Visual Studio 2017

environment:
  my_secret:
    secure: Zw+6liPcT9Ar/HhRas4Hwg==
  keystore_pw:
    secure: 1sehi0qb9TlwFvhfNXKeSQ==
  keystore_alias:
    secure: v/5FBX9yuKAKY5SWsdik9q0JA8ukHdKiApz8NzewQLpJKtCcCjmblZisXVv7eAb+63pcB4voM2FwMQn0RbJzzA==

init:
- appveyor version
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200`tapi.nuget.org")'

install:
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -decrypt C:\projects\app-cross-platform-j312l\keystore_file.jks.enc -secret %my_secret%

version: 2.1.{build}

configuration: AppStore

# Retain the NuGet package cache between builds.
cache:
 # - C:\Users\appveyor\AppData\Local\NuGet\Cache
 # - '%USERPROFILE%\.nuget\packages-> **\packages.config'
 # try 
  - C:\projects\app-cross-platform-j312l\packages

#shallow_clone: true
platform: Any CPU

# restore packages
before_build:
  - nuget restore 
build_script:
  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release CPU" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=%keystore_alias%" "/p:AndroidSigningKeyPass=%keystore_pw%" "/p:AndroidSigningKeyStore=keystore-integreat.jks" "/p:AndroidSigningStorePass=refugee" "C:\projects\app-cross-platform-j312l\Integreat\Integreat.Droid\Integreat.Droid.csproj"

artifacts:
  - path: C:\projects\app-cross-platform-j312l\Integreat\Integreat.Droid\bin\Release\tuerantuer.app.integreat-Signed.apk

build:
  verbosity: minimal
