init:
- appveyor version

image: Visual Studio 2017
install:
- cmd: nuget sources remove -name nuget.org
- cmd: nuget sources add -name nuget.org -Source https://api.nuget.org/v3/index.json

version: 2.0.{build}

configuration: AppStore

# Retain the NuGet package cache between builds.
cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

#shallow_clone: true
platform: Any CPU

# restore packages
before_build:
  - nuget restore -DisableParallelProcessing

build:
  verbosity: minimal
